# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver_wireguard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='driver_wireguard.proto',
  package='abbot',
  syntax='proto3',
  serialized_options=b'Z\037arhat.dev/abbot-proto/abbotgopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x64river_wireguard.proto\x12\x05\x61\x62\x62ot\"\xf0\x02\n\x0f\x44riverWireguard\x12\x11\n\tlog_level\x18\x01 \x01(\t\x12\x13\n\x0bprivate_key\x18\x02 \x01(\t\x12\x13\n\x0blisten_port\x18\x03 \x01(\x05\x12/\n\x07routing\x18\x04 \x01(\x0b\x32\x1e.abbot.DriverWireguard.Routing\x12*\n\x05peers\x18\x05 \x03(\x0b\x32\x1b.abbot.DriverWireguard.Peer\x1a\x80\x01\n\x04Peer\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x16\n\x0epre_shared_key\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12%\n\x1dpersistent_keepalive_interval\x18\x04 \x01(\x03\x12\x13\n\x0b\x61llowed_ips\x18\x05 \x03(\t\x1a@\n\x07Routing\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\r\n\x05table\x18\x02 \x01(\x05\x12\x15\n\rfirewall_mark\x18\x03 \x01(\x05\x42!Z\x1f\x61rhat.dev/abbot-proto/abbotgopbb\x06proto3'
)




_DRIVERWIREGUARD_PEER = _descriptor.Descriptor(
  name='Peer',
  full_name='abbot.DriverWireguard.Peer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='abbot.DriverWireguard.Peer.public_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pre_shared_key', full_name='abbot.DriverWireguard.Peer.pre_shared_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='abbot.DriverWireguard.Peer.endpoint', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='persistent_keepalive_interval', full_name='abbot.DriverWireguard.Peer.persistent_keepalive_interval', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allowed_ips', full_name='abbot.DriverWireguard.Peer.allowed_ips', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=336,
)

_DRIVERWIREGUARD_ROUTING = _descriptor.Descriptor(
  name='Routing',
  full_name='abbot.DriverWireguard.Routing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='abbot.DriverWireguard.Routing.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='table', full_name='abbot.DriverWireguard.Routing.table', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='firewall_mark', full_name='abbot.DriverWireguard.Routing.firewall_mark', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=402,
)

_DRIVERWIREGUARD = _descriptor.Descriptor(
  name='DriverWireguard',
  full_name='abbot.DriverWireguard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='log_level', full_name='abbot.DriverWireguard.log_level', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='private_key', full_name='abbot.DriverWireguard.private_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='listen_port', full_name='abbot.DriverWireguard.listen_port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='routing', full_name='abbot.DriverWireguard.routing', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peers', full_name='abbot.DriverWireguard.peers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DRIVERWIREGUARD_PEER, _DRIVERWIREGUARD_ROUTING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=402,
)

_DRIVERWIREGUARD_PEER.containing_type = _DRIVERWIREGUARD
_DRIVERWIREGUARD_ROUTING.containing_type = _DRIVERWIREGUARD
_DRIVERWIREGUARD.fields_by_name['routing'].message_type = _DRIVERWIREGUARD_ROUTING
_DRIVERWIREGUARD.fields_by_name['peers'].message_type = _DRIVERWIREGUARD_PEER
DESCRIPTOR.message_types_by_name['DriverWireguard'] = _DRIVERWIREGUARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DriverWireguard = _reflection.GeneratedProtocolMessageType('DriverWireguard', (_message.Message,), {

  'Peer' : _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), {
    'DESCRIPTOR' : _DRIVERWIREGUARD_PEER,
    '__module__' : 'driver_wireguard_pb2'
    # @@protoc_insertion_point(class_scope:abbot.DriverWireguard.Peer)
    })
  ,

  'Routing' : _reflection.GeneratedProtocolMessageType('Routing', (_message.Message,), {
    'DESCRIPTOR' : _DRIVERWIREGUARD_ROUTING,
    '__module__' : 'driver_wireguard_pb2'
    # @@protoc_insertion_point(class_scope:abbot.DriverWireguard.Routing)
    })
  ,
  'DESCRIPTOR' : _DRIVERWIREGUARD,
  '__module__' : 'driver_wireguard_pb2'
  # @@protoc_insertion_point(class_scope:abbot.DriverWireguard)
  })
_sym_db.RegisterMessage(DriverWireguard)
_sym_db.RegisterMessage(DriverWireguard.Peer)
_sym_db.RegisterMessage(DriverWireguard.Routing)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
