# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver_bridge.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='driver_bridge.proto',
  package='abbot',
  syntax='proto3',
  serialized_options=b'Z\037arhat.dev/abbot-proto/abbotgopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x64river_bridge.proto\x12\x05\x61\x62\x62ot\"\xcd\x01\n\x0c\x44riverBridge\x12\r\n\x05\x41lias\x18\x01 \x01(\t\x12\x0e\n\x06TxQLen\x18\x02 \x01(\x05\x12\x0f\n\x07Promisc\x18\x03 \x01(\x08\x12\x0f\n\x07Hairpin\x18\x0c \x01(\x08\x12\r\n\x05Guard\x18\r \x01(\x08\x12\x11\n\tFastLeave\x18\x0e \x01(\x08\x12\x11\n\tRootBlock\x18\x0f \x01(\x08\x12\x10\n\x08Learning\x18\x10 \x01(\x08\x12\r\n\x05\x46lood\x18\x11 \x01(\x08\x12\x10\n\x08ProxyArp\x18\x12 \x01(\x08\x12\x14\n\x0cProxyArpWiFi\x18\x13 \x01(\x08\x42!Z\x1f\x61rhat.dev/abbot-proto/abbotgopbb\x06proto3'
)




_DRIVERBRIDGE = _descriptor.Descriptor(
  name='DriverBridge',
  full_name='abbot.DriverBridge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Alias', full_name='abbot.DriverBridge.Alias', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TxQLen', full_name='abbot.DriverBridge.TxQLen', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Promisc', full_name='abbot.DriverBridge.Promisc', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Hairpin', full_name='abbot.DriverBridge.Hairpin', index=3,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Guard', full_name='abbot.DriverBridge.Guard', index=4,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FastLeave', full_name='abbot.DriverBridge.FastLeave', index=5,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RootBlock', full_name='abbot.DriverBridge.RootBlock', index=6,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Learning', full_name='abbot.DriverBridge.Learning', index=7,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Flood', full_name='abbot.DriverBridge.Flood', index=8,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProxyArp', full_name='abbot.DriverBridge.ProxyArp', index=9,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProxyArpWiFi', full_name='abbot.DriverBridge.ProxyArpWiFi', index=10,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=236,
)

DESCRIPTOR.message_types_by_name['DriverBridge'] = _DRIVERBRIDGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DriverBridge = _reflection.GeneratedProtocolMessageType('DriverBridge', (_message.Message,), {
  'DESCRIPTOR' : _DRIVERBRIDGE,
  '__module__' : 'driver_bridge_pb2'
  # @@protoc_insertion_point(class_scope:abbot.DriverBridge)
  })
_sym_db.RegisterMessage(DriverBridge)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
