# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver_unknown.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='driver_unknown.proto',
  package='abbot',
  syntax='proto3',
  serialized_options=b'Z\037arhat.dev/abbot-proto/abbotgopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x64river_unknown.proto\x12\x05\x61\x62\x62ot\"\x0f\n\rDriverUnknownB!Z\x1f\x61rhat.dev/abbot-proto/abbotgopbb\x06proto3'
)




_DRIVERUNKNOWN = _descriptor.Descriptor(
  name='DriverUnknown',
  full_name='abbot.DriverUnknown',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['DriverUnknown'] = _DRIVERUNKNOWN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DriverUnknown = _reflection.GeneratedProtocolMessageType('DriverUnknown', (_message.Message,), {
  'DESCRIPTOR' : _DRIVERUNKNOWN,
  '__module__' : 'driver_unknown_pb2'
  # @@protoc_insertion_point(class_scope:abbot.DriverUnknown)
  })
_sym_db.RegisterMessage(DriverUnknown)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
