# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meta.proto',
  package='abbot',
  syntax='proto3',
  serialized_options=b'Z\037arhat.dev/abbot-proto/abbotgopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmeta.proto\x12\x05\x61\x62\x62ot\"M\n\x10NetworkInterface\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\taddresses\x18\x02 \x03(\t\x12\x18\n\x10hardware_address\x18\x03 \x01(\tB!Z\x1f\x61rhat.dev/abbot-proto/abbotgopbb\x06proto3'
)




_NETWORKINTERFACE = _descriptor.Descriptor(
  name='NetworkInterface',
  full_name='abbot.NetworkInterface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='abbot.NetworkInterface.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='abbot.NetworkInterface.addresses', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hardware_address', full_name='abbot.NetworkInterface.hardware_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['NetworkInterface'] = _NETWORKINTERFACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetworkInterface = _reflection.GeneratedProtocolMessageType('NetworkInterface', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKINTERFACE,
  '__module__' : 'meta_pb2'
  # @@protoc_insertion_point(class_scope:abbot.NetworkInterface)
  })
_sym_db.RegisterMessage(NetworkInterface)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
