# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto.proto',
  package='abbot',
  syntax='proto3',
  serialized_options=b'Z\037arhat.dev/abbot-proto/abbotgopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bproto.proto\x12\x05\x61\x62\x62ot\"9\n\x07Request\x12 \n\x04kind\x18\x01 \x01(\x0e\x32\x12.abbot.RequestType\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\";\n\x08Response\x12!\n\x04kind\x18\x01 \x01(\x0e\x32\x13.abbot.ResponseType\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c*\x9f\x02\n\x0bRequestType\x12\x14\n\x10_INVALID_REQUEST\x10\x00\x12!\n\x1dREQ_ENSURE_CTR_NETWORK_CONFIG\x10\x0b\x12 \n\x1cREQ_QUERY_CTR_NETWORK_CONFIG\x10\x0c\x12\x1a\n\x16REQ_ENSURE_CTR_NETWORK\x10\x15\x12\x1b\n\x17REQ_RESTORE_CTR_NETWORK\x10\x16\x12\x1a\n\x16REQ_DELETE_CTR_NETWORK\x10\x17\x12\x19\n\x15REQ_QUERY_CTR_NETWORK\x10\x18\x12\"\n\x1eREQ_ENSURE_HOST_NETWORK_CONFIG\x10\x1f\x12!\n\x1dREQ_QUERY_HOST_NETWORK_CONFIG\x10 *\xae\x01\n\x0cResponseType\x12\x15\n\x11_INVALID_RESPONSE\x10\x00\x12\r\n\tRESP_DONE\x10\x01\x12\x1b\n\x17RESP_CTR_NETWORK_CONFIG\x10\x0b\x12\x1b\n\x17RESP_CTR_NETWORK_STATUS\x10\x15\x12 \n\x1cRESP_CTR_NETWORK_STATUS_LIST\x10\x16\x12\x1c\n\x18RESP_HOST_NETWORK_CONFIG\x10\x1f\x42!Z\x1f\x61rhat.dev/abbot-proto/abbotgopbb\x06proto3'
)

_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='abbot.RequestType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_INVALID_REQUEST', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQ_ENSURE_CTR_NETWORK_CONFIG', index=1, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQ_QUERY_CTR_NETWORK_CONFIG', index=2, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQ_ENSURE_CTR_NETWORK', index=3, number=21,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQ_RESTORE_CTR_NETWORK', index=4, number=22,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQ_DELETE_CTR_NETWORK', index=5, number=23,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQ_QUERY_CTR_NETWORK', index=6, number=24,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQ_ENSURE_HOST_NETWORK_CONFIG', index=7, number=31,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQ_QUERY_HOST_NETWORK_CONFIG', index=8, number=32,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=143,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTYPE)

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='abbot.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_INVALID_RESPONSE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESP_DONE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESP_CTR_NETWORK_CONFIG', index=2, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESP_CTR_NETWORK_STATUS', index=3, number=21,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESP_CTR_NETWORK_STATUS_LIST', index=4, number=22,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESP_HOST_NETWORK_CONFIG', index=5, number=31,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=433,
  serialized_end=607,
)
_sym_db.RegisterEnumDescriptor(_RESPONSETYPE)

ResponseType = enum_type_wrapper.EnumTypeWrapper(_RESPONSETYPE)
_INVALID_REQUEST = 0
REQ_ENSURE_CTR_NETWORK_CONFIG = 11
REQ_QUERY_CTR_NETWORK_CONFIG = 12
REQ_ENSURE_CTR_NETWORK = 21
REQ_RESTORE_CTR_NETWORK = 22
REQ_DELETE_CTR_NETWORK = 23
REQ_QUERY_CTR_NETWORK = 24
REQ_ENSURE_HOST_NETWORK_CONFIG = 31
REQ_QUERY_HOST_NETWORK_CONFIG = 32
_INVALID_RESPONSE = 0
RESP_DONE = 1
RESP_CTR_NETWORK_CONFIG = 11
RESP_CTR_NETWORK_STATUS = 21
RESP_CTR_NETWORK_STATUS_LIST = 22
RESP_HOST_NETWORK_CONFIG = 31



_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='abbot.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='abbot.Request.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='abbot.Request.body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=79,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='abbot.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='abbot.Response.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='abbot.Response.body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=140,
)

_REQUEST.fields_by_name['kind'].enum_type = _REQUESTTYPE
_RESPONSE.fields_by_name['kind'].enum_type = _RESPONSETYPE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['RequestType'] = _REQUESTTYPE
DESCRIPTOR.enum_types_by_name['ResponseType'] = _RESPONSETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'proto_pb2'
  # @@protoc_insertion_point(class_scope:abbot.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'proto_pb2'
  # @@protoc_insertion_point(class_scope:abbot.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
