/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "cni.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(abbot_CNICapArgs, abbot_CNICapArgs, AUTO)


PB_BIND(abbot_CNICapArgs_PortMap, abbot_CNICapArgs_PortMap, AUTO)


PB_BIND(abbot_CNICapArgs_Bandwidth, abbot_CNICapArgs_Bandwidth, AUTO)


PB_BIND(abbot_CNICapArgs_IPRange, abbot_CNICapArgs_IPRange, AUTO)


PB_BIND(abbot_CNICapArgs_DNSConfig, abbot_CNICapArgs_DNSConfig, AUTO)


PB_BIND(abbot_CreateOptions, abbot_CreateOptions, AUTO)


PB_BIND(abbot_CreateOptions_CniArgsEntry, abbot_CreateOptions_CniArgsEntry, AUTO)


PB_BIND(abbot_ConfigOptions, abbot_ConfigOptions, AUTO)


PB_BIND(abbot_GetAddrOptions, abbot_GetAddrOptions, AUTO)


PB_BIND(abbot_UpdateLinkOptions, abbot_UpdateLinkOptions, AUTO)


PB_BIND(abbot_RestoreLinkOptions, abbot_RestoreLinkOptions, AUTO)


PB_BIND(abbot_DeleteLinkOptions, abbot_DeleteLinkOptions, AUTO)


PB_BIND(abbot_Request, abbot_Request, AUTO)


PB_BIND(abbot_Response, abbot_Response, AUTO)


PB_BIND(abbot_AddressResponse, abbot_AddressResponse, AUTO)


PB_BIND(abbot_EmptyResponse, abbot_EmptyResponse, AUTO)




