/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "container.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(abbot_CNICapArgs, abbot_CNICapArgs, AUTO)


PB_BIND(abbot_CNICapArgs_PortMap, abbot_CNICapArgs_PortMap, AUTO)


PB_BIND(abbot_CNICapArgs_Bandwidth, abbot_CNICapArgs_Bandwidth, AUTO)


PB_BIND(abbot_CNICapArgs_IPRange, abbot_CNICapArgs_IPRange, AUTO)


PB_BIND(abbot_CNICapArgs_DNSConfig, abbot_CNICapArgs_DNSConfig, AUTO)


PB_BIND(abbot_CNICapArgs_IPAddresses, abbot_CNICapArgs_IPAddresses, AUTO)


PB_BIND(abbot_CNICapArgs_MacAddress, abbot_CNICapArgs_MacAddress, AUTO)


PB_BIND(abbot_CNICapArgs_InfinibandGUID, abbot_CNICapArgs_InfinibandGUID, AUTO)


PB_BIND(abbot_CNICapArgs_DeviceID, abbot_CNICapArgs_DeviceID, AUTO)


PB_BIND(abbot_ContainerNetworkEnsureRequest, abbot_ContainerNetworkEnsureRequest, AUTO)


PB_BIND(abbot_ContainerNetworkEnsureRequest_CniArgsEntry, abbot_ContainerNetworkEnsureRequest_CniArgsEntry, AUTO)


PB_BIND(abbot_ContainerNetworkRestoreRequest, abbot_ContainerNetworkRestoreRequest, AUTO)


PB_BIND(abbot_ContainerNetworkDeleteRequest, abbot_ContainerNetworkDeleteRequest, AUTO)


PB_BIND(abbot_ContainerNetworkConfigEnsureRequest, abbot_ContainerNetworkConfigEnsureRequest, AUTO)


PB_BIND(abbot_ContainerNetworkConfigQueryRequest, abbot_ContainerNetworkConfigQueryRequest, AUTO)


PB_BIND(abbot_ContainerNetworkQueryRequest, abbot_ContainerNetworkQueryRequest, AUTO)


PB_BIND(abbot_ContainerNetworkConfigResponse, abbot_ContainerNetworkConfigResponse, AUTO)


PB_BIND(abbot_ContainerNetworkStatusResponse, abbot_ContainerNetworkStatusResponse, AUTO)


PB_BIND(abbot_ContainerNetworkStatusListResponse, abbot_ContainerNetworkStatusListResponse, AUTO)


PB_BIND(abbot_ContainerNetworkStatusListResponse_ContainerNetworksEntry, abbot_ContainerNetworkStatusListResponse_ContainerNetworksEntry, AUTO)



