/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ABBOT_DRIVER_BRIDGE_PB_H_INCLUDED
#define PB_ABBOT_DRIVER_BRIDGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _abbot_DriverBridge {
    pb_callback_t Alias;
    int32_t TxQLen;
    bool Promisc;
    bool Hairpin;
    bool Guard;
    bool FastLeave;
    bool RootBlock;
    bool Learning;
    bool Flood;
    bool ProxyArp;
    bool ProxyArpWiFi;
} abbot_DriverBridge;


/* Initializer values for message structs */
#define abbot_DriverBridge_init_default          {{{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define abbot_DriverBridge_init_zero             {{{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define abbot_DriverBridge_Alias_tag             1
#define abbot_DriverBridge_TxQLen_tag            2
#define abbot_DriverBridge_Promisc_tag           3
#define abbot_DriverBridge_Hairpin_tag           12
#define abbot_DriverBridge_Guard_tag             13
#define abbot_DriverBridge_FastLeave_tag         14
#define abbot_DriverBridge_RootBlock_tag         15
#define abbot_DriverBridge_Learning_tag          16
#define abbot_DriverBridge_Flood_tag             17
#define abbot_DriverBridge_ProxyArp_tag          18
#define abbot_DriverBridge_ProxyArpWiFi_tag      19

/* Struct field encoding specification for nanopb */
#define abbot_DriverBridge_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   Alias,             1) \
X(a, STATIC,   SINGULAR, INT32,    TxQLen,            2) \
X(a, STATIC,   SINGULAR, BOOL,     Promisc,           3) \
X(a, STATIC,   SINGULAR, BOOL,     Hairpin,          12) \
X(a, STATIC,   SINGULAR, BOOL,     Guard,            13) \
X(a, STATIC,   SINGULAR, BOOL,     FastLeave,        14) \
X(a, STATIC,   SINGULAR, BOOL,     RootBlock,        15) \
X(a, STATIC,   SINGULAR, BOOL,     Learning,         16) \
X(a, STATIC,   SINGULAR, BOOL,     Flood,            17) \
X(a, STATIC,   SINGULAR, BOOL,     ProxyArp,         18) \
X(a, STATIC,   SINGULAR, BOOL,     ProxyArpWiFi,     19)
#define abbot_DriverBridge_CALLBACK pb_default_field_callback
#define abbot_DriverBridge_DEFAULT NULL

extern const pb_msgdesc_t abbot_DriverBridge_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define abbot_DriverBridge_fields &abbot_DriverBridge_msg

/* Maximum encoded size of messages (where known) */
/* abbot_DriverBridge_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
