/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "host.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(abbot_HostNetworkInterface, abbot_HostNetworkInterface, AUTO)


PB_BIND(abbot_HostNetworkConfigEnsureRequest, abbot_HostNetworkConfigEnsureRequest, AUTO)


PB_BIND(abbot_HostNetworkConfigQueryRequest, abbot_HostNetworkConfigQueryRequest, AUTO)


PB_BIND(abbot_HostNetworkStatusResponse, abbot_HostNetworkStatusResponse, AUTO)



