/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ABBOT_META_PB_H_INCLUDED
#define PB_ABBOT_META_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _abbot_InterfaceInfo {
    pb_callback_t name;
    pb_callback_t addresses;
} abbot_InterfaceInfo;


/* Initializer values for message structs */
#define abbot_InterfaceInfo_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define abbot_InterfaceInfo_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define abbot_InterfaceInfo_name_tag             1
#define abbot_InterfaceInfo_addresses_tag        2

/* Struct field encoding specification for nanopb */
#define abbot_InterfaceInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, STRING,   addresses,         2)
#define abbot_InterfaceInfo_CALLBACK pb_default_field_callback
#define abbot_InterfaceInfo_DEFAULT NULL

extern const pb_msgdesc_t abbot_InterfaceInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define abbot_InterfaceInfo_fields &abbot_InterfaceInfo_msg

/* Maximum encoded size of messages (where known) */
/* abbot_InterfaceInfo_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
